services:
  - type: web
    name: ip
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: IPQUALITY_ARGS
        value: "-p -j -4"
      - key: IPQUALITY_TIMEOUT
        value: "240"
